use super::{CentralChrWriter, DirectWriter};
use crate::mapper165::{
    SELECT_CENTRAL_RIGHT_FE_CHR_BANK_ADDRESS, SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    SELECT_LEFT_FE_CHR_BANK_ADDRESS, SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    SELECT_RIGHT_FD_CHR_BANK_FOR_PAIR_ADDRESS, SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
};

pub(in crate::mapper165) const CENTRAL_CHR_WRITERS: &[CentralChrWriter] = &[
    CentralChrWriter {
        role: "PPU $0000 FD source",
        source_address: 0xC9AE,
        shadow_address: 0x59,
        source_register: 0xB000,
        target_routine: SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    },
    CentralChrWriter {
        role: "PPU $0000 FE source",
        source_address: 0xC9B6,
        shadow_address: 0x5A,
        source_register: 0xC000,
        target_routine: SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    },
    CentralChrWriter {
        role: "PPU $1000 FD source",
        source_address: 0xC9BE,
        shadow_address: 0x5B,
        source_register: 0xD000,
        target_routine: SELECT_RIGHT_FD_CHR_BANK_FOR_PAIR_ADDRESS,
    },
    CentralChrWriter {
        role: "PPU $1000 FE source",
        source_address: 0xC9C6,
        shadow_address: 0x5C,
        source_register: 0xE000,
        target_routine: SELECT_CENTRAL_RIGHT_FE_CHR_BANK_ADDRESS,
    },
];

pub(in crate::mapper165) const DIRECT_CHR_WRITERS: &[DirectWriter] = &[
    DirectWriter::switchable(
        "bank 05 left FD initialization",
        0x05,
        0x810E,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 left FE initialization",
        0x05,
        0x8113,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 left FD reset",
        0x05,
        0x85E9,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 left FE reset",
        0x05,
        0x85EC,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 right FD reset",
        0x05,
        0x880E,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 right FE reset",
        0x05,
        0x8811,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 alternate left FD reset",
        0x05,
        0x8D25,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 05 alternate left FE reset",
        0x05,
        0x8D28,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    battle_left_fd_chr_writer("terrain preview sprite page $16 selection", 0x962F),
    battle_left_fd_chr_writer("battle effect-object sprite page $08 selection", 0xA2F8),
    battle_left_fd_chr_writer("battle effect-object sprite page $08 selection", 0xA382),
    battle_left_fd_chr_writer("battle effect-object sprite page $09 selection", 0xA3D6),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA413),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA527),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA584),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA642),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA6DE),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA77E),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA807),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA86E),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xA890),
    battle_left_fd_chr_writer("battle effect-object sprite page $0C selection", 0xA911),
    battle_left_fd_chr_writer("battle effect-object sprite page $0C selection", 0xA962),
    battle_left_fd_chr_writer("battle effect-object sprite page $0C selection", 0xA9A1),
    battle_left_fd_chr_writer("battle effect-object sprite page $0C selection", 0xA9F1),
    battle_left_fd_chr_writer("battle effect-object sprite page $0D selection", 0xAA64),
    battle_left_fd_chr_writer("battle effect-object sprite page $0E selection", 0xAAD1),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xAB16),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xAB69),
    battle_left_fd_chr_writer("battle effect-object sprite page $17 selection", 0xACB6),
    DirectWriter::switchable(
        "bank 07 left FD reset",
        0x07,
        0xAC35,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 07 left FE reset",
        0x07,
        0xAC38,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 07 right FD reset",
        0x07,
        0xAC3B,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 07 right FE reset",
        0x07,
        0xAC3E,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B first left FD reset",
        0x0B,
        0x9BF2,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B first left FE reset",
        0x0B,
        0x9BF5,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B first right FD reset",
        0x0B,
        0x9BF8,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B first right FE reset",
        0x0B,
        0x9BFB,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B second left FD reset",
        0x0B,
        0x9EAE,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B second left FE reset",
        0x0B,
        0x9EB1,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B second right FD reset",
        0x0B,
        0x9EB4,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "bank 0B second right FE reset",
        0x0B,
        0x9EB7,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "automatic status right FD source",
        0x0D,
        0x8036,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "automatic status right FE source",
        0x0D,
        0x8039,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "automatic status left FD source",
        0x0D,
        0x83AB,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::switchable(
        "automatic status left FE source",
        0x0D,
        0x83AE,
        0xC000,
        SELECT_LEFT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "reset right FD source",
        0xC1B7,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "reset right FE source",
        0xC1BA,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "NMI right FD source",
        0xC1F2,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "NMI right FE source",
        0xC1F7,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "screen clear right FD source",
        0xCF28,
        0xD000,
        SELECT_RIGHT_FD_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "screen clear right FE source",
        0xCF2B,
        0xE000,
        SELECT_RIGHT_FE_CHR_BANK_ADDRESS,
    ),
    DirectWriter::fixed(
        "unit data left FD source",
        0xE414,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    ),
];

const fn battle_left_fd_chr_writer(role: &'static str, source_address: u16) -> DirectWriter {
    DirectWriter::switchable(
        role,
        0x05,
        source_address,
        0xB000,
        SELECT_LEFT_FD_CHR_BANK_ADDRESS,
    )
}
