[workspace]
resolver = "2"
members = ["apps/fc_fire_emblem_patch"]

[workspace.package]
edition = "2024"
license = "GPL-2.0-or-later"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
fontdue = "0.9"
png = "0.18"
retro-rp2a03 = { package = "rp2a03", git = "https://github.com/mcpads/retro-typed-isa.git", rev = "7afd6a33df7b91198f9bdd3bd1c992d1a211d5de" }
typed-isa-core = { git = "https://github.com/mcpads/retro-typed-isa.git", rev = "7afd6a33df7b91198f9bdd3bd1c992d1a211d5de" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
