use super::*;

pub(super) const PPU_STORE_SITES: &[PpuStoreSite] = &[
    PpuStoreSite {
        role: "bank 0D visible-tile clear address high",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x8499,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "bank 0D visible-tile clear address low",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x849E,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "bank 0D visible-tile clear data",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x84AB,
        kind: PpuStoreKind::Data,
    },
    PpuStoreSite {
        role: "bank 0D attribute clear address high",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x84BB,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "bank 0D attribute clear address low",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x84C0,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "bank 0D attribute clear data",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x84C7,
        kind: PpuStoreKind::Data,
    },
    PpuStoreSite {
        role: "bank 0D composite text address high",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x84F7,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "bank 0D composite text address low",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x84FC,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "bank 0D composite text data",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x850D,
        kind: PpuStoreKind::Data,
    },
    PpuStoreSite {
        role: "bank 0D composite mark address high",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x8544,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "bank 0D composite mark address low",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x8549,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "bank 0D composite mark data",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x854D,
        kind: PpuStoreKind::Data,
    },
    PpuStoreSite {
        role: "bank 0D composite text resume address high",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x8563,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "bank 0D composite text resume address low",
        location: PrgLocation::Switchable(0x0D),
        cpu_address: 0x8568,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "fixed nametable clear address high",
        location: PrgLocation::Fixed,
        cpu_address: 0xC26C,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "fixed nametable clear address low",
        location: PrgLocation::Fixed,
        cpu_address: 0xC271,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "fixed nametable clear data",
        location: PrgLocation::Fixed,
        cpu_address: 0xC27A,
        kind: PpuStoreKind::Data,
    },
    PpuStoreSite {
        role: "fixed palette address high",
        location: PrgLocation::Fixed,
        cpu_address: 0xC2BD,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "fixed palette address low",
        location: PrgLocation::Fixed,
        cpu_address: 0xC2C2,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "fixed palette latch reset address high",
        location: PrgLocation::Fixed,
        cpu_address: 0xC2C5,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "fixed palette latch reset address low",
        location: PrgLocation::Fixed,
        cpu_address: 0xC2C8,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "fixed queued transfer address high",
        location: PrgLocation::Fixed,
        cpu_address: 0xC3BF,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "fixed queued transfer address low",
        location: PrgLocation::Fixed,
        cpu_address: 0xC3C5,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "fixed queued transfer data",
        location: PrgLocation::Fixed,
        cpu_address: 0xC3DD,
        kind: PpuStoreKind::Data,
    },
    PpuStoreSite {
        role: "fixed buffer transfer address high",
        location: PrgLocation::Fixed,
        cpu_address: 0xD4EC,
        kind: PpuStoreKind::AddressHigh,
    },
    PpuStoreSite {
        role: "fixed buffer transfer address low",
        location: PrgLocation::Fixed,
        cpu_address: 0xD4F2,
        kind: PpuStoreKind::AddressLow,
    },
    PpuStoreSite {
        role: "fixed buffer transfer data",
        location: PrgLocation::Fixed,
        cpu_address: 0xD501,
        kind: PpuStoreKind::Data,
    },
];
