use super::{ending_source::ENDING_SEQUENCE_PHASE_POINTERS_BYTES, *};

pub(super) fn regular_save_reachability() -> RegularSaveReachability {
    RegularSaveReachability {
        file_one_data_start_address: 0x6000,
        file_one_data_start_address_hex: "0x6000",
        file_one_data_end_exclusive_address: 0x6542,
        file_one_data_end_exclusive_address_hex: "0x6542",
        file_one_chapter_address: 0x6519,
        file_one_chapter_address_hex: "0x6519",
        file_one_checksum_address: 0x6542,
        file_one_checksum_address_hex: "0x6542",
        checksum_byte_order: "little-endian",
        checksum_algorithm: "16-bit wrapping sum of every byte in 0x6000..0x6542",
        chapter_number_basis: "one-based MAP number; the E5 intro context later writes the zero-based value to 0x781D",
        runtime_use: "reachability intervention only; change the chapter byte and recompute the checksum before selecting regular file one",
        natural_progression_claimed: false,
    }
}

pub(super) fn save_offer_no_branch_contract() -> SaveOfferNoBranchContract {
    SaveOfferNoBranchContract {
        screen_role: "chapter_save_offer",
        outer_screen_state_address: 0x0024,
        outer_screen_state_address_hex: "0x0024",
        offer_outer_screen_state: 0x0D,
        offer_outer_screen_state_hex: "0x0D",
        main_state_address: 0x0084,
        main_state_address_hex: "0x0084",
        owned_main_state_sequence: [0x07, 0x08, 0x09, 0x00],
        owned_main_state_sequence_hex: ["0x07", "0x08", "0x09", "0x00"],
        menu_depth_address: 0x05CE,
        menu_depth_address_hex: "0x05CE",
        observed_menu_depth: 0x02,
        active_selection_address: 0x7FF4,
        active_selection_address_hex: "0x7FF4",
        default_yes_selection: 0x01,
        no_selection: 0x02,
        committed_result_address: 0x05EB,
        committed_result_address_hex: "0x05EB",
        no_committed_result: 0x02,
        no_branch_exit_outer_state: 0x01,
        no_branch_exit_outer_state_hex: "0x01",
        no_branch_blackout_chr_pair: chr_pair(0x1B, 0x1B, 0x18, 0x18),
        persistent_save_route_entered: false,
        next_role: "chapter_transition_blackout",
        stable_sample_offsets_frames: [0, 7, 19, 43, 82, 171, 308, 565],
        stable_sample_screenshot_sha256: "a05ea43bc1844701650cfee6d441862d16d60fc1f7f0035704ce15dbbcfb352c",
        runtime_evidence: "with menu depth 02, Down changed only active selection slot 0x7FF4 from 01 to 02; A committed 02 to 0x05EB, main state advanced 07->08->09->00, bank 06:B76E wrote outer state 01, the no-save blackout used CHR 1B/1B + 18/18, and the next chapter map loaded without visiting the save-complete prompt",
    }
}

pub(super) fn save_complete_no_branch_contract() -> SaveCompleteNoBranchContract {
    SaveCompleteNoBranchContract {
        screen_role: "chapter_save_complete_continue_prompt",
        outer_screen_state_address: 0x0024,
        outer_screen_state_address_hex: "0x0024",
        outer_screen_state: 0x0E,
        outer_screen_state_hex: "0x0E",
        main_state_address: 0x0084,
        main_state_address_hex: "0x0084",
        main_state: 0x04,
        main_state_hex: "0x04",
        dialogue_substate_address: 0x05EE,
        dialogue_substate_address_hex: "0x05EE",
        owned_dialogue_substate_sequence: [0x07, 0x08, 0x09, 0x0A],
        owned_dialogue_substate_sequence_hex: ["0x07", "0x08", "0x09", "0x0A"],
        menu_depth_address: 0x05CE,
        menu_depth_address_hex: "0x05CE",
        observed_menu_depth: 0x03,
        active_selection_address: 0x7FF5,
        active_selection_address_hex: "0x7FF5",
        default_yes_selection: 0x01,
        no_selection: 0x02,
        committed_result_address: 0x05EB,
        committed_result_address_hex: "0x05EB",
        no_committed_result: 0x02,
        next_role: "chapter_save_complete_power_off_notice",
        notice_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
        notice_draw_sample_offsets_frames: [1, 11, 30, 67, 130, 259, 516, 900],
        settled_notice_sample_offsets_frames: [130, 259, 516, 900],
        settled_notice_screenshot_sha256: "c7e16901de2ed4e73c3cc6534e8a478e07ae61630ab7f7b43120f352f7c03ff1",
        hidden_unlock_progress_address: 0x775B,
        hidden_unlock_progress_address_hex: "0x775B",
        hidden_unlock_input_bytes: [0x08, 0x04, 0x02, 0x01, 0x08, 0x80],
        hidden_unlock_inputs: ["up", "down", "left", "right", "up", "A"],
        hidden_unlock_next_role: "sound_test",
        sound_test_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
        sound_test_translation_handling: "preserve original English labels and digits",
        runtime_evidence: "with menu depth 03, Down changed active selection slot 0x7FF5 from 01 to 02; A committed 02 to 0x05EB and advanced dialogue substates 07->08->09->0A while outer state 0E and main state 04 remained; the Japanese data-loss power-off notice settled by frame 130 and remained pixel-stable through frame 900; the source-bound up, down, left, right, up, A sequence advanced 0x775B and entered substate 0C, where the original-English sound test became visible",
    }
}

pub(super) fn sound_test_control_contract() -> SoundTestControlContract {
    SoundTestControlContract {
        screen_role: "sound_test",
        input_address: 0x0018,
        input_address_hex: "0x0018",
        sound_number_address: 0x775C,
        sound_number_address_hex: "0x775C",
        initial_sound_number: 0x00,
        upper_boundary: 0x50,
        upper_boundary_hex: "0x50",
        sound_event_base_address: 0x06F0,
        sound_event_base_address_hex: "0x06F0",
        sound_event_slot_count: 8,
        controls: vec![
            SoundTestControl {
                input: "up",
                input_mask: 0x08,
                input_mask_hex: "0x08",
                source_effect: "increment 0x775C; values at or above 0x50 wrap to 0x00; redraw the sound number and selected event bit",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "down",
                input_mask: 0x04,
                input_mask_hex: "0x04",
                source_effect: "decrement 0x775C; a negative result wraps to 0x50; redraw the sound number and selected event bit",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "A",
                input_mask: 0x80,
                input_mask_hex: "0x80",
                source_effect: "map 0x775C to one of eight event slots at 0x06F0 and write the matching one-hot bit",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "B",
                input_mask: 0x40,
                input_mask_hex: "0x40",
                source_effect: "write 0x01 to the base sound-event slot 0x06F0",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "Start",
                input_mask: 0x10,
                input_mask_hex: "0x10",
                source_effect: "increment dialogue substate 0x0C to 0x0D and tail-dispatch bank 0x07 handler index 0x03",
                next_dialogue_substate: Some(0x0D),
                downstream_family_role: Some("battle_animation_test_sequence"),
            },
            SoundTestControl {
                input: "Select",
                input_mask: 0x20,
                input_mask_hex: "0x20",
                source_effect: "increment dialogue substate 0x0C twice to 0x0E, prepare the ending state, then run substate 0x0F through bank 0x04 handler index 0x04",
                next_dialogue_substate: Some(0x0E),
                downstream_family_role: Some("ending_sequence"),
            },
        ],
        downstream_families: vec![
            DownstreamFamilyContract {
                family_role: "battle_animation_test_sequence",
                entry_dialogue_substate: 0x0D,
                prg_bank: 0x07,
                prg_bank_hex: "0x07",
                bank_handler_index: 0x03,
                bank_handler_index_hex: "0x03",
                entry_point: 0xAA2B,
                entry_point_hex: "0xAA2B",
                phase_state_address: 0x7730,
                phase_state_address_hex: "0x7730",
                phase_pointer_count: BATTLE_ANIMATION_TEST_PHASE_POINTERS_BYTES.len() / 2,
                static_flow: "the bank handler runs a dedicated loop and dispatches six source phases from 0x7730",
                runtime_observed: true,
                screen_partition_status: "the six source phases reach 0x7730=0x05 before the visible battle sequence; the remaining lifetimes reuse the shared battle_animation role rather than forming six screens",
                visible_screen_roles: &["battle_animation"],
                translation_scope_status: "Japanese battle labels and messages are translation targets; existing Latin abbreviations and digits remain preserved",
            },
            DownstreamFamilyContract {
                family_role: "ending_sequence",
                entry_dialogue_substate: 0x0E,
                prg_bank: 0x04,
                prg_bank_hex: "0x04",
                bank_handler_index: 0x04,
                bank_handler_index_hex: "0x04",
                entry_point: 0x9EC6,
                entry_point_hex: "0x9EC6",
                phase_state_address: 0x7731,
                phase_state_address_hex: "0x7731",
                phase_pointer_count: ENDING_SEQUENCE_PHASE_POINTERS_BYTES.len() / 2,
                static_flow: "substate 0x0E prepares ending memory; substate 0x0F loops bank 0x04 handler 0x04, which initializes and dispatches thirty source phases from 0x7731",
                runtime_observed: true,
                screen_partition_status: "the no-input route partitions phase 0x01 into a preserved opening-and-cast scroll and a Japanese-bearing chapter-record scroll, followed by preserved staff credits, phase-0x10 Japanese character epilogues, and the phase-0x1D static final signature",
                visible_screen_roles: &[
                    "ending_opening_and_cast_scroll",
                    "ending_chapter_record_scroll",
                    "ending_staff_credits",
                    "ending_character_epilogue",
                    "ending_final_signature",
                ],
                translation_scope_status: "translate Japanese chapter records and character epilogues only; preserve the original English story, cast, staff, signature, copyright, Roman names, and digits",
            },
        ],
        controls_runtime_observed: true,
        translation_handling: "preserve every original English label and digit on the sound-test screen",
        proof_boundary: "runtime verifies selector wrap, transient A and B sound-event writes, Start's repeating shared battle lifetimes, and Select's automatic mixed-language ending through its static terminal phase; source content and translation remain outside this structural contract",
    }
}

pub(super) fn chapter_intro_runtime_samples() -> Vec<ChapterIntroRuntimeSample> {
    vec![
        ChapterIntroRuntimeSample {
            sample_role: "chapter_two_intro",
            chapter_number_one_based: 2,
            chapter_index_zero_based: 1,
            entry_method: "natural chapter-one completion and regular-save cold load",
            left_fd_chr_page: 0x13,
            left_fe_chr_page: 0x13,
            right_fd_chr_page: 0x00,
            right_fe_chr_page: 0x18,
            portrait_visible_in_sample: true,
            completion_marker_phase_union_observed: false,
            proof_limit: "binds the chapter-two composite only",
        },
        ChapterIntroRuntimeSample {
            sample_role: "chapter_eleven_intro",
            chapter_number_one_based: 11,
            chapter_index_zero_based: 10,
            entry_method: "chapter-one regular save with file-one chapter and checksum changed in a frozen isolated run",
            left_fd_chr_page: 0x1A,
            left_fe_chr_page: 0x1A,
            right_fd_chr_page: 0x00,
            right_fe_chr_page: 0x18,
            portrait_visible_in_sample: false,
            completion_marker_phase_union_observed: true,
            proof_limit: "proves chapter-eleven intro reachability and a distinct left CHR pair, not chapter-ten completion or the full transition sequence",
        },
        ChapterIntroRuntimeSample {
            sample_role: "chapter_twelve_intro",
            chapter_number_one_based: 12,
            chapter_index_zero_based: 11,
            entry_method: "continuous chapter-eleven しろ, four-page epilogue, default-yes save, automatic blackout, and continue route with declared movement and HP progression accelerations; the same CHR pair was previously reached by a checksummed cold load",
            left_fd_chr_page: 0x0F,
            left_fe_chr_page: 0x0F,
            right_fd_chr_page: 0x00,
            right_fe_chr_page: 0x18,
            portrait_visible_in_sample: true,
            completion_marker_phase_union_observed: true,
            proof_limit: "proves the continuous accelerated route and a distinct left CHR pair, not baseline difficulty, unaccelerated combat equivalence, defeat, or unfavorable branches",
        },
    ]
}

pub(super) fn transition_screens() -> Vec<TransitionScreen> {
    vec![
        TransitionScreen {
            route_stage: 1,
            route_membership: &[
                "save_and_continue",
                "skip_save_and_continue",
                "save_and_stop",
                "sound_test_unlock",
            ],
            screen_role: "chapter_clear_epilogue_dialogue",
            entry_condition: "the chapter objective resolves and the chapter-clear epilogue begins over the retained map",
            runtime_observed: true,
            input_behavior: "mixed",
            visible_components: &[
                "retained chapter map and unit sprites",
                "portrait",
                "dialogue window and Japanese text",
                "possibly flashing completion marker",
            ],
            translation_target: "Japanese dialogue only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0C, "0x0C", 0x3C, "0x3C", Some(0x02), Some(0x0E)),
            observed_chr_pair: chr_pair(0x11, 0x11, 0x00, 0x18),
            temporal_behavior: "four observed page variants draw automatically and then wait for A; portrait visibility was true, true, false, true",
            input_actions: &[InputAction {
                input: "A on a completed page",
                immediate_effect: "advance the epilogue page; the terminal page enters next_story_banner",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "chapter_clear_epilogue_dialogue or next_story_banner",
            }],
            focus_elements: &[
                "page count and terminal page",
                "portrait presence per page",
                "completion-marker phase union",
                "retained-map and CHR variants",
            ],
            unresolved_focus: &["remaining chapter-specific epilogue page and portrait variants"],
        },
        TransitionScreen {
            route_stage: 2,
            route_membership: &[
                "save_and_continue",
                "skip_save_and_continue",
                "save_and_stop",
                "sound_test_unlock",
            ],
            screen_role: "next_story_banner",
            entry_condition: "the chapter-clear epilogue dialogue reaches its terminal transition",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "retained chapter map and unit sprites",
                "centered window",
                "original English NEXT STORY label",
            ],
            translation_target: "none",
            preserved_original: &["NEXT STORY"],
            runtime_state: runtime_state(0x0D, "0x0D", 0x03, "0x03", Some(0x00), Some(0x00)),
            observed_chr_pair: chr_pair(0x1B, 0x1B, 0x00, 0x18),
            temporal_behavior: "the banner remained visible for 1,200 input-free frames",
            input_actions: &[InputAction {
                input: "A",
                immediate_effect: "close the banner and open the chapter save offer",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "chapter_save_offer",
            }],
            focus_elements: &[
                "preserved original English label",
                "input-wait duration",
                "retained-map animation",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 3,
            route_membership: &[
                "save_and_continue",
                "skip_save_and_continue",
                "save_and_stop",
                "sound_test_unlock",
            ],
            screen_role: "chapter_save_offer",
            entry_condition: "NEXT STORY is dismissed",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "retained chapter map and unit sprites",
                "small centered Japanese save question",
                "yes and no choice window",
                "selection cursor",
            ],
            translation_target: "Japanese question and choices only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0D, "0x0D", 0x07, "0x07", None, None),
            observed_chr_pair: chr_pair(0x1B, 0x1B, 0x00, 0x18),
            temporal_behavior: "the selected-no composite was pixel-stable at irregular offsets through 565 input-free frames",
            input_actions: &[
                InputAction {
                    input: "up or down",
                    immediate_effect: "change the yes or no selection",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_save_offer",
                },
                InputAction {
                    input: "A on the observed default yes choice",
                    immediate_effect: "write the chapter-clear save and open the save-complete continue prompt",
                    may_cause_persistent_gameplay_mutation: true,
                    next_role: "chapter_save_complete_continue_prompt",
                },
                InputAction {
                    input: "A on the observed no choice",
                    immediate_effect: "skip the save-complete prompt, close through main states 08 and 09, and enter the no-save blackout",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_transition_blackout",
                },
            ],
            focus_elements: &[
                "Japanese question and choices",
                "active selection slot at menu depth 02",
                "persistent-save boundary on yes",
                "prompt bypass and blackout variant on no",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 4,
            route_membership: &["save_and_continue", "save_and_stop", "sound_test_unlock"],
            screen_role: "chapter_save_complete_continue_prompt",
            entry_condition: "the observed chapter-clear save finishes",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "retained chapter map and unit sprites",
                "portrait",
                "large dialogue window with Japanese save-complete and continue text",
                "yes and no choice window",
                "selection cursor",
            ],
            translation_target: "Japanese dialogue and choices only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0E, "0x0E", 0x04, "0x04", None, Some(0x11)),
            observed_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
            temporal_behavior: "the selected-no composite was pixel-stable at eight irregular offsets through 565 input-free frames",
            input_actions: &[
                InputAction {
                    input: "up or down",
                    immediate_effect: "change the yes or no selection through active slot 0x7FF5",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_save_complete_continue_prompt",
                },
                InputAction {
                    input: "A on the observed default yes choice",
                    immediate_effect: "continue from the completed save into the automatic black transition",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_transition_blackout",
                },
                InputAction {
                    input: "A on the observed no choice",
                    immediate_effect: "close the choice window, draw the data-loss power-off notice, and remain in outer state 0E",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_save_complete_power_off_notice",
                },
            ],
            focus_elements: &[
                "Japanese save-complete dialogue and choices",
                "active selection slot at menu depth 03",
                "portrait and retained-map composition",
                "continue-versus-stop branch ownership",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 5,
            route_membership: &["save_and_stop", "sound_test_unlock"],
            screen_role: "chapter_save_complete_power_off_notice",
            entry_condition: "A commits no on the save-complete continue prompt",
            runtime_observed: true,
            input_behavior: "terminal_instruction_with_hidden_unlock",
            visible_components: &[
                "retained chapter map and unit sprites",
                "portrait",
                "large dialogue window with a Japanese data-loss power-off notice",
                "completion marker",
            ],
            translation_target: "Japanese notice only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0E, "0x0E", 0x04, "0x04", None, Some(0x11)),
            observed_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
            temporal_behavior: "the notice drew automatically through dialogue substates 08 and 09, settled at substate 0A by frame 130, and remained pixel-stable through frame 900",
            input_actions: &[InputAction {
                input: "up, down, left, right, up, A",
                immediate_effect: "advance the source-bound hidden sequence at 0x775B and enter the sound test after all six inputs match",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "sound_test",
            }],
            focus_elements: &[
                "Japanese terminal instruction",
                "automatic text-draw versus settled wait",
                "retained portrait and map",
                "hidden sound-test input sequence",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 6,
            route_membership: &["sound_test_unlock"],
            screen_role: "sound_test",
            entry_condition: "the six-input hidden sequence completes on the power-off notice",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "black background",
                "original English SOUND TEST MODE label",
                "original English sound and interface labels",
                "sound-number digits",
            ],
            translation_target: "none",
            preserved_original: &["all English labels", "digits"],
            runtime_state: runtime_state(0x0E, "0x0E", 0x04, "0x04", None, None),
            observed_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
            temporal_behavior: "the hidden sequence entered substate 0B, cleared the old composition, and displayed the sound test at substate 0C without further input",
            input_actions: &[
                InputAction {
                    input: "up or down",
                    immediate_effect: "change sound number 0x775C with source-defined wraparound and redraw its number and event bit",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "sound_test",
                },
                InputAction {
                    input: "A",
                    immediate_effect: "map the selected sound number to one event slot at 0x06F0..0x06F7 and write its one-hot bit",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "sound_test",
                },
                InputAction {
                    input: "B",
                    immediate_effect: "write 01 to the base sound-event slot 0x06F0",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "sound_test",
                },
                InputAction {
                    input: "Start",
                    immediate_effect: "advance to substate 0D and enter bank-07 handler 03; the outer six phases settle into the automatic shared battle-animation lifetimes",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "battle_animation",
                },
                InputAction {
                    input: "Select",
                    immediate_effect: "advance through substates 0E and 0F into bank-04 handler 04; the automatic ending begins with the preserved opening-and-cast scroll",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "ending_opening_and_cast_scroll",
                },
            ],
            focus_elements: &[
                "preserve every original English label and digit",
                "runtime-observed sound-number selection and transient event writes",
                "Start's repeating shared battle lifetimes",
                "Select's automatic preserved and Japanese ending lifetimes through the static terminal signature",
            ],
            unresolved_focus: &[
                "the remaining character-epilogue temporal glyph, portrait, speaker, CHR, nametable, and sprite variants",
            ],
        },
        TransitionScreen {
            route_stage: 5,
            route_membership: &["save_and_continue", "skip_save_and_continue"],
            screen_role: "chapter_transition_blackout",
            entry_condition: "the observed default-yes continue choice leaves the save-complete prompt, or the observed save-offer no choice skips that prompt",
            runtime_observed: true,
            input_behavior: "automatic",
            visible_components: &["full black frame"],
            translation_target: "none",
            preserved_original: &[],
            runtime_state: runtime_state(0x09, "0x09", 0x00, "0x00", None, None),
            observed_chr_pair: chr_pair(0x1A, 0x1A, 0x18, 0x18),
            temporal_behavior: "both observed full-black routes advance without input; the save route used outer state 09 and the no-save route wrote outer state 01",
            input_actions: &[],
            focus_elements: &[
                "absence of text",
                "automatic advance without input",
                "save and no-save outer-state variants",
                "CHR lifetime before the next map",
            ],
            unresolved_focus: &[
                "remaining chapter-specific transition timing",
                "the complete outer-state lifetime after the no-save route writes 01",
            ],
        },
        TransitionScreen {
            route_stage: 6,
            route_membership: &["save_and_continue", "skip_save_and_continue"],
            screen_role: "chapter_intro_title_dialogue_composite",
            entry_condition: "chapter-clear continuation or a cold load enters a chapter introduction",
            runtime_observed: true,
            input_behavior: "mixed",
            visible_components: &[
                "new chapter map and unit sprites",
                "chapter title bar with protected original number and Japanese title",
                "portrait",
                "dialogue window and Japanese text layered below the title bar",
                "possibly flashing completion marker",
            ],
            translation_target: "Japanese chapter title and dialogue only",
            preserved_original: &["chapter-number digits"],
            runtime_state: runtime_state(0x0B, "0x0B", 0x00, "0x00", None, Some(0x0E)),
            observed_chr_pair: chr_pair(0x0F, 0x0F, 0x00, 0x18),
            temporal_behavior: "the title bar remains while dialogue draws automatically and completed pages wait for input",
            input_actions: &[InputAction {
                input: "A on a completed dialogue page",
                immediate_effect: "advance the chapter-intro dialogue without changing the retained title contract",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "chapter_intro_title_dialogue_composite or the chapter map",
            }],
            focus_elements: &[
                "Japanese title and dialogue as separate text owners",
                "protected chapter-number digits",
                "portrait presence and completion-marker phases",
                "title-bar exit relative to the final dialogue page",
            ],
            unresolved_focus: &[
                "title-bar exit lifetime relative to the final dialogue page",
                "chapter-specific map, portrait, and CHR variants after chapter 2",
            ],
        },
    ]
}

pub(super) const fn runtime_state(
    outer_screen_state: u8,
    outer_screen_state_hex: &'static str,
    main_state: u8,
    main_state_hex: &'static str,
    victory_stage: Option<u8>,
    dialogue_state: Option<u8>,
) -> RuntimeScreenState {
    RuntimeScreenState {
        outer_screen_state,
        outer_screen_state_hex,
        main_state,
        main_state_hex,
        victory_stage,
        dialogue_state,
    }
}

pub(super) const fn chr_pair(left_fd: u8, left_fe: u8, right_fd: u8, right_fe: u8) -> ChrPair {
    ChrPair {
        left_fd,
        left_fe,
        right_fd,
        right_fe,
    }
}
