use super::*;

pub(super) fn chapter_intro_runtime_samples() -> Vec<ChapterIntroRuntimeSample> {
    vec![
        ChapterIntroRuntimeSample {
            sample_role: "chapter_two_intro",
            chapter_number_one_based: 2,
            chapter_index_zero_based: 1,
            entry_method: "natural chapter-one completion and regular-save cold load",
            left_fd_chr_page: 0x13,
            left_fe_chr_page: 0x13,
            right_fd_chr_page: 0x00,
            right_fe_chr_page: 0x18,
            portrait_visible_in_sample: true,
            completion_marker_phase_union_observed: false,
            proof_limit: "binds the chapter-two composite only",
        },
        ChapterIntroRuntimeSample {
            sample_role: "chapter_eleven_intro",
            chapter_number_one_based: 11,
            chapter_index_zero_based: 10,
            entry_method: "chapter-one regular save with file-one chapter and checksum changed in a frozen isolated run",
            left_fd_chr_page: 0x1A,
            left_fe_chr_page: 0x1A,
            right_fd_chr_page: 0x00,
            right_fe_chr_page: 0x18,
            portrait_visible_in_sample: false,
            completion_marker_phase_union_observed: true,
            proof_limit: "proves chapter-eleven intro reachability and a distinct left CHR pair, not chapter-ten completion or the full transition sequence",
        },
        ChapterIntroRuntimeSample {
            sample_role: "chapter_twelve_intro",
            chapter_number_one_based: 12,
            chapter_index_zero_based: 11,
            entry_method: "continuous chapter-eleven しろ, four-page epilogue, default-yes save, automatic blackout, and continue route with declared movement and HP progression accelerations; the same CHR pair was previously reached by a checksummed cold load",
            left_fd_chr_page: 0x0F,
            left_fe_chr_page: 0x0F,
            right_fd_chr_page: 0x00,
            right_fe_chr_page: 0x18,
            portrait_visible_in_sample: true,
            completion_marker_phase_union_observed: true,
            proof_limit: "proves the continuous accelerated route and a distinct left CHR pair, not baseline difficulty, unaccelerated combat equivalence, defeat, or unfavorable branches",
        },
    ]
}

pub(super) fn transition_screens() -> Vec<TransitionScreen> {
    vec![
        TransitionScreen {
            route_stage: 1,
            route_membership: &[
                "save_and_continue",
                "skip_save_and_continue",
                "save_and_stop",
                "sound_test_unlock",
            ],
            screen_role: "chapter_clear_epilogue_dialogue",
            entry_condition: "the chapter objective resolves and the chapter-clear epilogue begins over the retained map",
            runtime_observed: true,
            input_behavior: "mixed",
            visible_components: &[
                "retained chapter map and unit sprites",
                "portrait",
                "dialogue window and Japanese text",
                "possibly flashing completion marker",
            ],
            translation_target: "Japanese dialogue only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0C, "0x0C", 0x3C, "0x3C", Some(0x02), Some(0x0E)),
            observed_chr_pair: chr_pair(0x11, 0x11, 0x00, 0x18),
            temporal_behavior: "four observed page variants draw automatically and then wait for A; portrait visibility was true, true, false, true",
            input_actions: &[InputAction {
                input: "A on a completed page",
                immediate_effect: "advance the epilogue page; the terminal page enters next_story_banner",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "chapter_clear_epilogue_dialogue or next_story_banner",
            }],
            focus_elements: &[
                "page count and terminal page",
                "portrait presence per page",
                "completion-marker phase union",
                "retained-map and CHR variants",
            ],
            unresolved_focus: &["remaining chapter-specific epilogue page and portrait variants"],
        },
        TransitionScreen {
            route_stage: 2,
            route_membership: &[
                "save_and_continue",
                "skip_save_and_continue",
                "save_and_stop",
                "sound_test_unlock",
            ],
            screen_role: "next_story_banner",
            entry_condition: "the chapter-clear epilogue dialogue reaches its terminal transition",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "retained chapter map and unit sprites",
                "centered window",
                "original English NEXT STORY label",
            ],
            translation_target: "none",
            preserved_original: &["NEXT STORY"],
            runtime_state: runtime_state(0x0D, "0x0D", 0x03, "0x03", Some(0x00), Some(0x00)),
            observed_chr_pair: chr_pair(0x1B, 0x1B, 0x00, 0x18),
            temporal_behavior: "the banner remained visible for 1,200 input-free frames",
            input_actions: &[InputAction {
                input: "A",
                immediate_effect: "close the banner and open the chapter save offer",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "chapter_save_offer",
            }],
            focus_elements: &[
                "preserved original English label",
                "input-wait duration",
                "retained-map animation",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 3,
            route_membership: &[
                "save_and_continue",
                "skip_save_and_continue",
                "save_and_stop",
                "sound_test_unlock",
            ],
            screen_role: "chapter_save_offer",
            entry_condition: "NEXT STORY is dismissed",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "retained chapter map and unit sprites",
                "small centered Japanese save question",
                "yes and no choice window",
                "selection cursor",
            ],
            translation_target: "Japanese question and choices only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0D, "0x0D", 0x07, "0x07", None, None),
            observed_chr_pair: chr_pair(0x1B, 0x1B, 0x00, 0x18),
            temporal_behavior: "the selected-no composite was pixel-stable at irregular offsets through 565 input-free frames",
            input_actions: &[
                InputAction {
                    input: "up or down",
                    immediate_effect: "change the yes or no selection",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_save_offer",
                },
                InputAction {
                    input: "A on the observed default yes choice",
                    immediate_effect: "write the chapter-clear save and open the save-complete continue prompt",
                    may_cause_persistent_gameplay_mutation: true,
                    next_role: "chapter_save_complete_continue_prompt",
                },
                InputAction {
                    input: "A on the observed no choice",
                    immediate_effect: "skip the save-complete prompt, close through main states 08 and 09, and enter the no-save blackout",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_transition_blackout",
                },
            ],
            focus_elements: &[
                "Japanese question and choices",
                "active selection slot at menu depth 02",
                "persistent-save boundary on yes",
                "prompt bypass and blackout variant on no",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 4,
            route_membership: &["save_and_continue", "save_and_stop", "sound_test_unlock"],
            screen_role: "chapter_save_complete_continue_prompt",
            entry_condition: "the observed chapter-clear save finishes",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "retained chapter map and unit sprites",
                "portrait",
                "large dialogue window with Japanese save-complete and continue text",
                "yes and no choice window",
                "selection cursor",
            ],
            translation_target: "Japanese dialogue and choices only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0E, "0x0E", 0x04, "0x04", None, Some(0x11)),
            observed_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
            temporal_behavior: "the selected-no composite was pixel-stable at eight irregular offsets through 565 input-free frames",
            input_actions: &[
                InputAction {
                    input: "up or down",
                    immediate_effect: "change the yes or no selection through active slot 0x7FF5",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_save_complete_continue_prompt",
                },
                InputAction {
                    input: "A on the observed default yes choice",
                    immediate_effect: "continue from the completed save into the automatic black transition",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_transition_blackout",
                },
                InputAction {
                    input: "A on the observed no choice",
                    immediate_effect: "close the choice window, draw the data-loss power-off notice, and remain in outer state 0E",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "chapter_save_complete_power_off_notice",
                },
            ],
            focus_elements: &[
                "Japanese save-complete dialogue and choices",
                "active selection slot at menu depth 03",
                "portrait and retained-map composition",
                "continue-versus-stop branch ownership",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 5,
            route_membership: &["save_and_stop", "sound_test_unlock"],
            screen_role: "chapter_save_complete_power_off_notice",
            entry_condition: "A commits no on the save-complete continue prompt",
            runtime_observed: true,
            input_behavior: "terminal_instruction_with_hidden_unlock",
            visible_components: &[
                "retained chapter map and unit sprites",
                "portrait",
                "large dialogue window with a Japanese data-loss power-off notice",
                "completion marker",
            ],
            translation_target: "Japanese notice only",
            preserved_original: &[],
            runtime_state: runtime_state(0x0E, "0x0E", 0x04, "0x04", None, Some(0x11)),
            observed_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
            temporal_behavior: "the notice drew automatically through dialogue substates 08 and 09, settled at substate 0A by frame 130, and remained pixel-stable through frame 900",
            input_actions: &[InputAction {
                input: "up, down, left, right, up, A",
                immediate_effect: "advance the source-bound hidden sequence at 0x775B and enter the sound test after all six inputs match",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "sound_test",
            }],
            focus_elements: &[
                "Japanese terminal instruction",
                "automatic text-draw versus settled wait",
                "retained portrait and map",
                "hidden sound-test input sequence",
            ],
            unresolved_focus: &["remaining chapter-specific retained-map variants"],
        },
        TransitionScreen {
            route_stage: 6,
            route_membership: &["sound_test_unlock"],
            screen_role: "sound_test",
            entry_condition: "the six-input hidden sequence completes on the power-off notice",
            runtime_observed: true,
            input_behavior: "input_wait",
            visible_components: &[
                "black background",
                "original English SOUND TEST MODE label",
                "original English sound and interface labels",
                "sound-number digits",
            ],
            translation_target: "none",
            preserved_original: &["all English labels", "digits"],
            runtime_state: runtime_state(0x0E, "0x0E", 0x04, "0x04", None, None),
            observed_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
            temporal_behavior: "the hidden sequence entered substate 0B, cleared the old composition, and displayed the sound test at substate 0C without further input",
            input_actions: &[
                InputAction {
                    input: "up or down",
                    immediate_effect: "change sound number 0x775C with source-defined wraparound and redraw its number and event bit",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "sound_test",
                },
                InputAction {
                    input: "A",
                    immediate_effect: "map the selected sound number to one event slot at 0x06F0..0x06F7 and write its one-hot bit",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "sound_test",
                },
                InputAction {
                    input: "B",
                    immediate_effect: "write 01 to the base sound-event slot 0x06F0",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "sound_test",
                },
                InputAction {
                    input: "Start",
                    immediate_effect: "advance to substate 0D and enter bank-07 handler 03; the outer six phases settle into the automatic shared battle-animation lifetimes",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "battle_animation",
                },
                InputAction {
                    input: "Select",
                    immediate_effect: "advance through substates 0E and 0F into bank-04 handler 04; the automatic ending begins with the preserved opening-and-cast scroll",
                    may_cause_persistent_gameplay_mutation: false,
                    next_role: "ending_opening_and_cast_scroll",
                },
            ],
            focus_elements: &[
                "preserve every original English label and digit",
                "runtime-observed sound-number selection and transient event writes",
                "Start's repeating shared battle lifetimes",
                "Select's automatic preserved and Japanese ending lifetimes through the static terminal signature",
            ],
            unresolved_focus: &[
                "the remaining character-epilogue temporal glyph, portrait, speaker, CHR, nametable, and sprite variants",
            ],
        },
        TransitionScreen {
            route_stage: 5,
            route_membership: &["save_and_continue", "skip_save_and_continue"],
            screen_role: "chapter_transition_blackout",
            entry_condition: "the observed default-yes continue choice leaves the save-complete prompt, or the observed save-offer no choice skips that prompt",
            runtime_observed: true,
            input_behavior: "automatic",
            visible_components: &["full black frame"],
            translation_target: "none",
            preserved_original: &[],
            runtime_state: runtime_state(0x09, "0x09", 0x00, "0x00", None, None),
            observed_chr_pair: chr_pair(0x1A, 0x1A, 0x18, 0x18),
            temporal_behavior: "both observed full-black routes advance without input; the save route used outer state 09 and the no-save route wrote outer state 01",
            input_actions: &[],
            focus_elements: &[
                "absence of text",
                "automatic advance without input",
                "save and no-save outer-state variants",
                "CHR lifetime before the next map",
            ],
            unresolved_focus: &[
                "remaining chapter-specific transition timing",
                "the complete outer-state lifetime after the no-save route writes 01",
            ],
        },
        TransitionScreen {
            route_stage: 6,
            route_membership: &["save_and_continue", "skip_save_and_continue"],
            screen_role: "chapter_intro_title_dialogue_composite",
            entry_condition: "chapter-clear continuation or a cold load enters a chapter introduction",
            runtime_observed: true,
            input_behavior: "mixed",
            visible_components: &[
                "new chapter map and unit sprites",
                "chapter title bar with protected original number and Japanese title",
                "portrait",
                "dialogue window and Japanese text layered below the title bar",
                "possibly flashing completion marker",
            ],
            translation_target: "Japanese chapter title and dialogue only",
            preserved_original: &["chapter-number digits"],
            runtime_state: runtime_state(0x0B, "0x0B", 0x00, "0x00", None, Some(0x0E)),
            observed_chr_pair: chr_pair(0x0F, 0x0F, 0x00, 0x18),
            temporal_behavior: "the title bar remains while dialogue draws automatically and completed pages wait for input",
            input_actions: &[InputAction {
                input: "A on a completed dialogue page",
                immediate_effect: "advance the chapter-intro dialogue without changing the retained title contract",
                may_cause_persistent_gameplay_mutation: false,
                next_role: "chapter_intro_title_dialogue_composite or the chapter map",
            }],
            focus_elements: &[
                "Japanese title and dialogue as separate text owners",
                "protected chapter-number digits",
                "portrait presence and completion-marker phases",
                "title-bar exit relative to the final dialogue page",
            ],
            unresolved_focus: &[
                "title-bar exit lifetime relative to the final dialogue page",
                "chapter-specific map, portrait, and CHR variants after chapter 2",
            ],
        },
    ]
}

pub(super) const fn runtime_state(
    outer_screen_state: u8,
    outer_screen_state_hex: &'static str,
    main_state: u8,
    main_state_hex: &'static str,
    victory_stage: Option<u8>,
    dialogue_state: Option<u8>,
) -> RuntimeScreenState {
    RuntimeScreenState {
        outer_screen_state,
        outer_screen_state_hex,
        main_state,
        main_state_hex,
        victory_stage,
        dialogue_state,
    }
}

pub(super) const fn chr_pair(left_fd: u8, left_fe: u8, right_fd: u8, right_fe: u8) -> ChrPair {
    ChrPair {
        left_fd,
        left_fe,
        right_fd,
        right_fe,
    }
}
