use super::*;

pub(super) fn regular_save_reachability() -> RegularSaveReachability {
    RegularSaveReachability {
        file_one_data_start_address: 0x6000,
        file_one_data_start_address_hex: "0x6000",
        file_one_data_end_exclusive_address: 0x6542,
        file_one_data_end_exclusive_address_hex: "0x6542",
        file_one_chapter_address: 0x6519,
        file_one_chapter_address_hex: "0x6519",
        file_one_checksum_address: 0x6542,
        file_one_checksum_address_hex: "0x6542",
        checksum_byte_order: "little-endian",
        checksum_algorithm: "16-bit wrapping sum of every byte in 0x6000..0x6542",
        chapter_number_basis: "one-based MAP number; the E5 intro context later writes the zero-based value to 0x781D",
        runtime_use: "reachability intervention only; change the chapter byte and recompute the checksum before selecting regular file one",
        natural_progression_claimed: false,
    }
}

pub(super) fn save_offer_no_branch_contract() -> SaveOfferNoBranchContract {
    SaveOfferNoBranchContract {
        screen_role: "chapter_save_offer",
        outer_screen_state_address: 0x0024,
        outer_screen_state_address_hex: "0x0024",
        offer_outer_screen_state: 0x0D,
        offer_outer_screen_state_hex: "0x0D",
        main_state_address: 0x0084,
        main_state_address_hex: "0x0084",
        owned_main_state_sequence: [0x07, 0x08, 0x09, 0x00],
        owned_main_state_sequence_hex: ["0x07", "0x08", "0x09", "0x00"],
        menu_depth_address: 0x05CE,
        menu_depth_address_hex: "0x05CE",
        observed_menu_depth: 0x02,
        active_selection_address: 0x7FF4,
        active_selection_address_hex: "0x7FF4",
        default_yes_selection: 0x01,
        no_selection: 0x02,
        committed_result_address: 0x05EB,
        committed_result_address_hex: "0x05EB",
        no_committed_result: 0x02,
        no_branch_exit_outer_state: 0x01,
        no_branch_exit_outer_state_hex: "0x01",
        no_branch_blackout_chr_pair: chr_pair(0x1B, 0x1B, 0x18, 0x18),
        persistent_save_route_entered: false,
        next_role: "chapter_transition_blackout",
        stable_sample_offsets_frames: [0, 7, 19, 43, 82, 171, 308, 565],
        stable_sample_screenshot_sha256: "a05ea43bc1844701650cfee6d441862d16d60fc1f7f0035704ce15dbbcfb352c",
        runtime_evidence: "with menu depth 02, Down changed only active selection slot 0x7FF4 from 01 to 02; A committed 02 to 0x05EB, main state advanced 07->08->09->00, bank 06:B76E wrote outer state 01, the no-save blackout used CHR 1B/1B + 18/18, and the next chapter map loaded without visiting the save-complete prompt",
    }
}

pub(super) fn save_complete_no_branch_contract() -> SaveCompleteNoBranchContract {
    SaveCompleteNoBranchContract {
        screen_role: "chapter_save_complete_continue_prompt",
        outer_screen_state_address: 0x0024,
        outer_screen_state_address_hex: "0x0024",
        outer_screen_state: 0x0E,
        outer_screen_state_hex: "0x0E",
        main_state_address: 0x0084,
        main_state_address_hex: "0x0084",
        main_state: 0x04,
        main_state_hex: "0x04",
        dialogue_substate_address: 0x05EE,
        dialogue_substate_address_hex: "0x05EE",
        owned_dialogue_substate_sequence: [0x07, 0x08, 0x09, 0x0A],
        owned_dialogue_substate_sequence_hex: ["0x07", "0x08", "0x09", "0x0A"],
        menu_depth_address: 0x05CE,
        menu_depth_address_hex: "0x05CE",
        observed_menu_depth: 0x03,
        active_selection_address: 0x7FF5,
        active_selection_address_hex: "0x7FF5",
        default_yes_selection: 0x01,
        no_selection: 0x02,
        committed_result_address: 0x05EB,
        committed_result_address_hex: "0x05EB",
        no_committed_result: 0x02,
        next_role: "chapter_save_complete_power_off_notice",
        notice_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
        notice_draw_sample_offsets_frames: [1, 11, 30, 67, 130, 259, 516, 900],
        settled_notice_sample_offsets_frames: [130, 259, 516, 900],
        settled_notice_screenshot_sha256: "c7e16901de2ed4e73c3cc6534e8a478e07ae61630ab7f7b43120f352f7c03ff1",
        hidden_unlock_progress_address: 0x775B,
        hidden_unlock_progress_address_hex: "0x775B",
        hidden_unlock_input_bytes: [0x08, 0x04, 0x02, 0x01, 0x08, 0x80],
        hidden_unlock_inputs: ["up", "down", "left", "right", "up", "A"],
        hidden_unlock_next_role: "sound_test",
        sound_test_chr_pair: chr_pair(0x1C, 0x1C, 0x00, 0x18),
        sound_test_translation_handling: "preserve original English labels and digits",
        runtime_evidence: "with menu depth 03, Down changed active selection slot 0x7FF5 from 01 to 02; A committed 02 to 0x05EB and advanced dialogue substates 07->08->09->0A while outer state 0E and main state 04 remained; the Japanese data-loss power-off notice settled by frame 130 and remained pixel-stable through frame 900; the source-bound up, down, left, right, up, A sequence advanced 0x775B and entered substate 0C, where the original-English sound test became visible",
    }
}
