use super::{
    ending_source::ENDING_SEQUENCE_PHASE_POINTERS_BYTES,
    sound_test_source::BATTLE_ANIMATION_TEST_PHASE_POINTERS_BYTES, *,
};

pub(super) fn sound_test_control_contract() -> SoundTestControlContract {
    SoundTestControlContract {
        screen_role: "sound_test",
        input_address: 0x0018,
        input_address_hex: "0x0018",
        sound_number_address: 0x775C,
        sound_number_address_hex: "0x775C",
        initial_sound_number: 0x00,
        upper_boundary: 0x50,
        upper_boundary_hex: "0x50",
        sound_event_base_address: 0x06F0,
        sound_event_base_address_hex: "0x06F0",
        sound_event_slot_count: 8,
        controls: vec![
            SoundTestControl {
                input: "up",
                input_mask: 0x08,
                input_mask_hex: "0x08",
                source_effect: "increment 0x775C; values at or above 0x50 wrap to 0x00; redraw the sound number and selected event bit",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "down",
                input_mask: 0x04,
                input_mask_hex: "0x04",
                source_effect: "decrement 0x775C; a negative result wraps to 0x50; redraw the sound number and selected event bit",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "A",
                input_mask: 0x80,
                input_mask_hex: "0x80",
                source_effect: "map 0x775C to one of eight event slots at 0x06F0 and write the matching one-hot bit",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "B",
                input_mask: 0x40,
                input_mask_hex: "0x40",
                source_effect: "write 0x01 to the base sound-event slot 0x06F0",
                next_dialogue_substate: None,
                downstream_family_role: None,
            },
            SoundTestControl {
                input: "Start",
                input_mask: 0x10,
                input_mask_hex: "0x10",
                source_effect: "increment dialogue substate 0x0C to 0x0D and tail-dispatch bank 0x07 handler index 0x03",
                next_dialogue_substate: Some(0x0D),
                downstream_family_role: Some("battle_animation_test_sequence"),
            },
            SoundTestControl {
                input: "Select",
                input_mask: 0x20,
                input_mask_hex: "0x20",
                source_effect: "increment dialogue substate 0x0C twice to 0x0E, prepare the ending state, then run substate 0x0F through bank 0x04 handler index 0x04",
                next_dialogue_substate: Some(0x0E),
                downstream_family_role: Some("ending_sequence"),
            },
        ],
        downstream_families: vec![
            DownstreamFamilyContract {
                family_role: "battle_animation_test_sequence",
                entry_dialogue_substate: 0x0D,
                prg_bank: 0x07,
                prg_bank_hex: "0x07",
                bank_handler_index: 0x03,
                bank_handler_index_hex: "0x03",
                entry_point: 0xAA2B,
                entry_point_hex: "0xAA2B",
                phase_state_address: 0x7730,
                phase_state_address_hex: "0x7730",
                phase_pointer_count: BATTLE_ANIMATION_TEST_PHASE_POINTERS_BYTES.len() / 2,
                static_flow: "the bank handler runs a dedicated loop and dispatches six source phases from 0x7730",
                runtime_observed: true,
                screen_partition_status: "the six source phases reach 0x7730=0x05 before the visible battle sequence; the remaining lifetimes reuse the shared battle_animation role rather than forming six screens",
                visible_screen_roles: &["battle_animation"],
                translation_scope_status: "Japanese battle labels and messages are translation targets; existing Latin abbreviations and digits remain preserved",
            },
            DownstreamFamilyContract {
                family_role: "ending_sequence",
                entry_dialogue_substate: 0x0E,
                prg_bank: 0x04,
                prg_bank_hex: "0x04",
                bank_handler_index: 0x04,
                bank_handler_index_hex: "0x04",
                entry_point: 0x9EC6,
                entry_point_hex: "0x9EC6",
                phase_state_address: 0x7731,
                phase_state_address_hex: "0x7731",
                phase_pointer_count: ENDING_SEQUENCE_PHASE_POINTERS_BYTES.len() / 2,
                static_flow: "substate 0x0E prepares ending memory; substate 0x0F loops bank 0x04 handler 0x04, which initializes and dispatches thirty source phases from 0x7731",
                runtime_observed: true,
                screen_partition_status: "the no-input route partitions phase 0x01 into a preserved opening-and-cast scroll and a Japanese-bearing chapter-record scroll, followed by preserved staff credits, phase-0x10 Japanese character epilogues, and the phase-0x1D static final signature",
                visible_screen_roles: &[
                    "ending_opening_and_cast_scroll",
                    "ending_chapter_record_scroll",
                    "ending_staff_credits",
                    "ending_character_epilogue",
                    "ending_final_signature",
                ],
                translation_scope_status: "translate Japanese chapter records and character epilogues only; preserve the original English story, cast, staff, signature, copyright, Roman names, and digits",
            },
        ],
        controls_runtime_observed: true,
        translation_handling: "preserve every original English label and digit on the sound-test screen",
        proof_boundary: "runtime verifies selector wrap, transient A and B sound-event writes, Start's repeating shared battle lifetimes, and Select's automatic mixed-language ending through its static terminal phase; source content and translation remain outside this structural contract",
    }
}
